### ISSUE TITLE
"Always allow from this sender" won't stick after logout then login

### ISSUE THREAD

**Issue by europacafe** [cypht-org/cypht#1161]
Cypht 2.1.0 + stalwart mail server

I understand that once I press "Always allow from this sender" for one mail (and it works for that mail), then I click to view another mail with the exact same sender (same email address), it should have shown the message images right away (I did this within the same Cypht login session), but sometimes I have to press "Always allow from this sender" again for the second mail.
I understand that upon allowing the sender, the sender's email address will be automatically populated in a sender whitelist.
![image](https://github.com/user-attachments/assets/3ecc4cce-d286-47ad-a1dc-367229458c0a)

I could not recognize the pattern of this issue.

Another relevant question is, should the auto-populated whitelist persist through subsequent Cypht login sessions without performing "Settings-->Save" on the previous session?

**Comment by jacob-js** [comment]
@europacafe The issue you just mentionned might have been introduced by some other new features or fixes to the codebase, this used to work how you just explained it. I should check to confirm.

> Another relevant question is, should the auto-populated whitelist persist through subsequent Cypht login sessions without performing "Settings-->Save" on the previous session?

The Settings save action does interact with everything related to the preferences of the application, not specifically the incoming data of emails, thus, implying that, whether external images are shown or not within the content of a message isn't a preference that should get saved as a session value, but instead, we leave to the user's browser to decide whether the resource is appropriate to be displayed or not. So yes, the whitelist should persist through subsequent logins.

**Comment by jacob-js** [comment]
https://github.com/cypht-org/cypht/pull/1166 should fix.

**Comment by marclaporte** [comment]
@Shadow243 Please advise

**Comment by europacafe** [comment]
Thanks. Just to inform docker image v2.2.0 still has this issue.

**Comment by Shadow243** [comment]
> docker image v2.2.0 still has this issue.
Copy that, working on it. Thanks.

**Comment by Shadow243** [comment]
> @Shadow243 Please advise

@Baraka24 i just merged this [https://github.com/cypht-org/cypht/pull/1166](https://github.com/cypht-org/cypht/pull/1166), can you confirm if it solved this issue please ?

**Comment by Baraka24** [comment]
I have tested with amailprivacytester.  @Shadow243 It works.

**Comment by europacafe** [comment]
The issue is still there with 2.3.0 docker.
I use Stalwart mail server.

**Comment by Shadow243** [comment]
> The issue is still there with 2.3.0 docker. I use Stalwart mail server.

Oh copy that, I reopen. Thanks for the feedback

**Comment by jacob-js** [comment]
> The issue is still there with 2.3.0 docker. I use Stalwart mail server.

@europacafe I don't know what commits are in there but, have you tried on master? If it behaves as unintended also, could you share the content of the email subjective of the issue with me if you consider it not confidential? So I could assist you better!

**Comment by europacafe** [comment]
Sorry, I still can't docker build from master successfully.

I found that once I allow image display from a mail address for the first mail, the other mails from the same sender will open images automatically. However, the "allow" permission won't survive after I logout and login again. So basically the "allow" permission is just temporary for that login session only.

**Comment by Shadow243** [comment]
> Sorry, I still can't docker build from master successfully.

`docker compose -f docker-compose.dev.yaml up` will run in dev mode.

**Comment by europacafe** [comment]
> Sorry, I still can't docker build from master successfully.
> 
> I found that once I allow image display from a mail address for the first mail, the other mails from the same sender will open images automatically. However, the "allow" permission won't survive after I logout and login again. So basically the "allow" permission is just temporary for that login session only.

I've successfully built the latest image based on the current master. The problem is still there.

**Comment by jacob-js** [comment]
@europacafe I think this ticket has drifted. The new issue you're raising—I'm not sure whether it's actually a matter of concern or not. I'm skeptical about whether the allowed resources should persist after logout or not. Let's see what others have to say about this.

**Comment by europacafe** [comment]
Thanks. Just FYI, I am also running Snappymail container accessing the same Stalwart mail server. Its "allow from sender" sticks permanently once allowed.

**Comment by marclaporte** [comment]
When I click "Always allow from this sender", I expect it to work until I remove the sender. In Cypht standalone, this will, I presume, require me to save the settings, which requires me to enter password to encrypt the new data.

If it was not "permanent", I would expect a button like "Allow from this sender for this session".

**Comment by jacob-js** [comment]
A message indicating that the action is session-limited has been added via https://github.com/cypht-org/cypht/pull/1295. However, there is still a need to ensure that whitelisted users are saved along with the settings.
