### ISSUE TITLE
Themes not working in 25707d6

### ISSUE THREAD

**Issue by PaulTGG** [cypht-org/cypht#1194]
## 🐛 Bugreport

A recent change has stopped themes from working.  Changing to any different theme does not change the appearance.

![Screenshot_2024-08-23_10-32-07](https://github.com/user-attachments/assets/312144c7-e66a-4203-827d-c3aba20c9841)

### Version & Environment

Rev: 25707d6

### Steps to reproduce
1. Run Cypht.

**Comment by Shadow243** [comment]
fixed at:
- [https://github.com/cypht-org/cypht/issues/1174](https://github.com/cypht-org/cypht/issues/1174)
- [https://github.com/cypht-org/cypht/pull/1214](https://github.com/cypht-org/cypht/pull/1214)

**Comment by PaulTGG** [comment]
> fixed at:
> 
>     * [Cypht menus, buttons, etc., showing codes instead of characters.  #1174](https://github.com/cypht-org/cypht/issues/1174)
> 
>     * [Fix Docker theme css path #1214](https://github.com/cypht-org/cypht/pull/1214)

The issue is not resolved for me.  I'm not running the docker image, and I just tried the latest master (18dc913) on a fresh install of Debian.  Have the install instructions changed recently?

**Comment by Shadow243** [comment]
>  I'll confirm once the merge happens

@PaulTGG  it's already merged, can you please confirm ?

**Comment by PaulTGG** [comment]
> @PaulTGG it's already merged, can you please confirm ?

Fixed!  Thanks!
