### ISSUE TITLE
multiple smtp servers are destroy when login out

### ISSUE THREAD

**Issue by ornais** [cypht-org/cypht#155]
When you configure multiple smtp servers, then save the "save" page, if you log out and log again to cypht, only the default smtp server remains.

**Comment by ornais** [comment]
If someone has the same issue:
If you don't configure a defaut smtp server. Everything works fine.

**Comment by jasonmunro** [comment]
Hi @ornais, thanks for this feedback. Sounds like we have a problem if this does not work with a default SMTP server. I am going to re-open and mark this as a bug.

**Comment by jasonmunro** [comment]
just retested this and it is resolved.

**Comment by outbackdingo** [comment]
This is still happening as of today in the latest git ... logout of ui after saving multiple smtp services, login, all but 2 are gone... i have 5 accounts in one domain. each is a different username@domain.com with separate password, it seems to only affect these accounts.

**Comment by myuseraccount** [comment]
This happens for me with the latest version.  I have to set a default server, because my username/email and password are a different domain than the mail server for my primary account.  I don't want it to have a visible domain selection drop-down at login.

**Comment by marclaporte** [comment]
@myuseraccount ok, I reopened the issue. Please come on the chatroom on https://gitter.im/cypht-org/community so we can pair you up with a developer to figure this out.

**Comment by myuseraccount** [comment]
I just stumbled on the /?save action under Settings.  That was all I had to do, works great and preserves my config after logout.

It would be great, if after entering servers and feeds, it would put text at the bottom or in the success notifications, telling you that you need to go to /?save for these settings to be preserved.  Or, just prompt for the password right there when making the changes, because why would you add those connections and not want to keep them?

**Comment by myuseraccount** [comment]
Also, I think this is what the poster was asking for in [this question about saving custom servers](https://github.com/cypht-org/cypht/issues/339), which quotes the text displayed on the /?save page.  I had the same thought: what is the configuration .env parameter that I must set before the /?save option will actually work?  Or what parameter tells the system to ignore saved changes and destroy the environment on logout?  Because when I log out, it actually says, "Session destroyed on logout" in the corner briefly, leading me to believe I lost the connections I added in my Settings.
